### ISSUE TITLE
please add progress event 

### ISSUE THREAD

**Issue by thecotne** [gkcgautam/Asset2SD#4]
so i can display progress bar and tell user witch resource is currently loading like some software installers do
also option to not override if file exists on SD

**Comment by gkcgautam** [comment]
Will release an alpha build soon. Can you help me in testing it?

**Comment by thecotne** [comment]
i have android device only at work so i will test it on Working days

Let's change the syntax make it more simple 
let's pass all params as one object like jQuery.ajax
it will look like this

```
asset2sd.copyFile({
    from: "www/images/photo.jpg",
    to: "funnyPhotos/photo.jpg",
    success: function(filePath){},
    error: function(errorMessage){},
    progress: function(progress){}
});
and for dir
asset2sd.copyDir({
    from: "www/images",
    to: "funnyPhotos",
    success: function(filePathArray){},
    error: function(errorMessage){},
    progress: function(progress){}
});
```

progress callback must have current copying filename 
files copyed and files left

i don't now programming in java but will help as i can ;)

**Comment by gkcgautam** [comment]
@thecotne Your syntax looks quite nice. I'll be adding progress part in next update once the current version gets properly tested. I made all of the changes without running even once! :grin:  
Will change to this syntax and also add support for preventing overwriting of files. Any other feature that we may need?

**Comment by thecotne** [comment]
i don't need but it may be useful for someone
exclude regexp for copydir

**Comment by gkcgautam** [comment]
regexp idea is good. We can have optional parameters 'include' (only copy files which match the pattern) and 'exclude' (copy all except those which match the pattern).
What do you think?

**Comment by thecotne** [comment]
i don't like 'include' idea because no one have that probably because no one need that as example 
[project](http://www.sublimetext.com/docs/3/projects.html) in sublime text 
has folder_exclude_patterns and file_exclude_patterns both are arrays and i think we need to support more simple pattern system then regexp 
sublime text has simple pattern system so this->"*.txt" is same as this-> /^.+.txt$/

also [KISS](http://en.wikipedia.org/wiki/KISS_principle) so it's not get complicated like [file API](http://docs.phonegap.com/en/3.0.0/cordova_file_file.md.html#File) in phonegap

**Comment by gkcgautam** [comment]
Ok. Will implement wildcard pattern matching.

**Comment by thecotne** [comment]
dos not work 

```
04-14 10:12:24.113 E/Asset2SD( 5693): Error occurred while copying file: /storage/sdcard/tuberkuliozi/video: open failed: EISDIR (Is a directory)
04-14 10:12:24.113 W/PluginManager( 5693): THREAD WARNING: exec() call to Asset2SD.copyFile blocked the main thread for 91ms. Plugin should use CordovaInterface.getThreadPool().
```

also old version worked for me but i don't now what happend 
it's not working also (with different error)

please fix this i really need this
before some new features please fix current version

**Comment by gkcgautam** [comment]
Please provide more details.
You were copying a single file or a folder?

On 4/14/14, cotne nazarashvili notifications@github.com wrote:

> dos not work
> 
> ```
> 04-14 10:12:24.113 E/Asset2SD( 5693): Error occurred while copying file:
> /storage/sdcard/tuberkuliozi/video: open failed: EISDIR (Is a directory)
> 04-14 10:12:24.113 W/PluginManager( 5693): THREAD WARNING: exec() call to
> Asset2SD.copyFile blocked the main thread for 91ms. Plugin should use
> CordovaInterface.getThreadPool().
> ```
> 
> also old version worked for me but i don't now what happend
> it's not working also (with different error)
> 
> please fix this i really need this
> before some new features please fix current version
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gkcgautam/Asset2SD/issues/4#issuecomment-40385580

## 

Regards,
Gautam Chaudhary
http://gautamchaudhary.com

**Comment by thecotne** [comment]
single file

**Comment by thecotne** [comment]
@gkcgautam any progress about fixing current version?

can't realize what was wrong but old version now works (current does not)

**Comment by gkcgautam** [comment]
@thecotne There was an error in README file usage example code. This might fix the problem. Sorry couldn't fix sooner.
https://github.com/gkcgautam/Asset2SD/commit/406af4baef253cce95b94d8dcedc9be7088e5d86

UPDATE
Turns out my ReadMe fix was wrong. Fixed again in https://github.com/gkcgautam/Asset2SD/commit/687c56ed2169db0d0a8ed2f1257f6f3a0ab4178c

**Comment by niyazafazl** [comment]
Hi,

I have used the asset2sd.copyDir plugin to copy the pdf file to SD card for my android phonegap app.
I installed the plugin using this  - 'cordova plugin add https://github.com/gkcgautam/Asset2SD.git'

When I run my app, all the functions have been called open the device ready, but the asset2sd.copyDir is not being fire anything, neither goes to success nor failure call.

Please advice whats wrong in this.

I have  included this in my androidmanifest.xml file as well.  
uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"

```
   function onDeviceReady() {
     alert("device ready");
      console.log(JSON.stringify(cordova.file));

      window.requestFileSystem  = window.requestFileSystem ||   window.webkitRequestFileSystem;
      window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, fsSuccess, fsFail);

 }      
  function copyPDF(file) {
  var bauxPDFDate = Math.floor(Date.now());
  localStorage.setItem("bauxPDFDate", JSON.stringify(bauxPDFDate));
   var timeNow = Math.floor(Date.now() / 1000);
   var timeLastDataBaux = localStorage.getItem("bauxPDFDate");
   // Don't copy the PDF for 15 min., it will be faster
   if(timeLastDataBaux > (timeNow-900)) // (60 * 15 = 900) 15 minutes de cache
   {           
    if(localStorage.getItem("bauxPDFDate") !== null)
     {
        alert("reached");
        // Display buttons to open PDFs
        $('#baux_page_loading').fadeOut('slow', function() {
            $('#baux_page_loaded').fadeIn('fast');
        });
        return true;
    }
    else
    {
    // ?
        console.log('First copy of files...');
    }
} 
  else 
  { 
  // Else, we have no data, or too old ? normal way => we launch the copy etc. 
    console.log('Files too old...');
   }

   asset2sd.copyDir({
      asset_directory: file, //"www/pdf"
      destination_directory: "MyTestDir"
      },
      function(result)
      {
        // SUCCESS !
        alert("dir copied" + result);
        $('#baux_page_loading').html('<p>✓ Well loaded&nbsp;!</p>');

        var timestamp = Math.floor(Date.now() / 1000);
        localStorage.setItem('bauxPDFDate', timestamp);

        // Display button to open PDFs
        $('#baux_page_loading').fadeOut('slow', function() {
            $('#baux_page_loaded').fadeIn('fast');
        });

      },
      function() {
        // ERROR
        alert("dir copied failed");
        $('#baux_page_loading').fadeOut('normal');
        $('#errorpdf').html('<div class="error">Impossible to load PDF files on the internal storage space or SD card (erreur : '+file+' - '+result+'). Please see our website <a onclick="http://www.example.com" class="coloredTap">www.example.com</a>  to download its PDF.</div>');
      }
      );
      }

    var fs;
        function fsSuccess(fileSystem)
            {
                fs = fileSystem;
             alert("fs name==>" +fs.name + "fs==>" + JSON.stringify(fs));
            }
        function fsFail(event)
            {
                console.log(event.target.error.code);
            }

   function openPDF(filename) {
        file = fs.root.toURL + filename;

        cordova.plugins.fileOpener2.open(
        file,
        'application/pdf',
        {
            error : function(e) {
            alert("Error:" + JSON.stringify(e));
                console.log('Error status: ' + e.status + ' - Error message: ' + e.message + '- Error:' + JSON.stringify(e));
               $('#errorpdf').html('Error status: ' + e.status + ' - Error message: ' + e.message);
            },
            success : function () {
            alert("pass");
                console.log('file opened successfully');
                $('#errorpdf').html('file opened successfully');

            }
        }
    );
    }
```

**Comment by uroatienza** [comment]
Hi @gkcgautam I plan to implement Asset2sd plugin in Ionic app but somehow can't make it work.
So far I only installed the plugin using CLI command - 'cordova plugin add https://github.com/gkcgautam/Asset2SD.git'
And now im lost what to do next. I wonder where should I put the code below. Should I create a js file for this and link it on my html?

asset2sd.copyDir({
        asset_directory: "www/images",
        destination_directory: "funnyPhotos"
    },
    function() { alert('success'); }, 
    function() { alert('fail'); }
);   

Hope to hear from you soon.
Many thanks in advance.
