### ISSUE TITLE
Returning  "fail". when i call asset2sd.copyFile().

### ISSUE THREAD

**Issue by shashikantkumar88** [gkcgautam/Asset2SD#5]
I want to copy pdf file asset to sd.
www\assets-- assets is a folder inside www 
asset2sd.copyFile(
             {
                asset_file: "www/assets/test.pdf",
                destination_file: "Test/test.pdf"
             },
            function() {
                alert("success");
            }, function() {
                alert("fail");
            });

Can you tell me?? what is the issue??

**Comment by gkcgautam** [comment]
I hope this README update would have solved this issue.
https://github.com/gkcgautam/Asset2SD/commit/406af4baef253cce95b94d8dcedc9be7088e5d86
